== Mock HTTP API server using python (recommended)

We provide a python implementation of this HTTP API server. It is not designed for production use.
but all the necessary steps, arguments extracting, basic authentication and authorization mechanism are provided in this script.
You can take this python code snippet to test and build your own API server using any language you'd prefer.

The python script is ready to use as python is a package pre-installed on most of the linux distros.
Please kindly check out the script in `/t/mock_servers/external_HTTP_API.py` from PacketFence repository, make any changes
necessary for debugging and troubleshooting.


== Mock HTTP API server by PHP
First install php on your server

Then add the following in /usr/local/pf/conf/httpd.conf.d/httpd.aaa.tt
```
Listen 10000
LoadModule php5_module modules/libphp5.so

<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>

<VirtualHost *:10000>
    DocumentRoot /usr/local/pf/addons/example_external_auth
</VirtualHost>
```

Then restart the httpd.aaa process and this will be available on port 10000

Make sure you also open the necessary ports in iptables (`/usr/local/pf/conf/iptables.conf`)

Note that this should only be used for testing purposes and IS NOT made for production purposes
